name: contexts-demo
on:
    workflow_dispatch:

env:
    MY_NAME: "Surendra"
    MY_JOB: "DevOps Engineer"

jobs:
    my_context_job:
        runs-on: ubuntu-latest
        env: 
            MY_NAME: "Josh"
            MY_JOB: "AI Engineer"
            MY_ADD: "Guntur" 

        steps:
            - name: first step
              env:
                 MY_NAME: "Kamal"
                 MY_JOB: "Principal Engineer"
                 MY_ADD: "Hyd" 

              run: |
                echo "this is context demo"
                echo "My name is ${{ env.MY_NAME }}"
                echo "My job is ${{ env.MY_JOB }}"
                echo "My Add is ${{env.MY_ADD}}"
                echo "MY SCHOOL IS ${{vars.SCHOOL}}"
                echo "MY Education is ${{vars.EDUCATION}}"
                echo "My secret is ${{secrets.MYPASSWORD}}"