name: event filters demo

on:
    pull_request: 

        branches: 
        - main
        paths:
        - 'surendra/**'

        types:
         - opened
         - synchronize



jobs:
    event-job:
        runs-on: ubuntu-slim
        steps:
            - name: my event job demo
              run: |
                echo "event job demo"
