name: event filters demo

on:
    push:
      branches:
      - main
      
    workflow_dispatch: 


jobs:
    event-job:
        runs-on: ubuntu-slim
        steps:
            - name: my event job demo
              run: |
                echo "event job demo"
