name: My first workflow
run-name: my job-first 

on:
  workflow_dispatch: 

jobs:
  myjob1:
    runs-on: ubuntu-latest
    steps:
      - name: displaying a msg
        run: echo "this is my first workflow"
      - name: hello
        run: |
          echo "how r u ?"
          echo "hi i am fine"

  
  myjob2:
    runs-on: ubuntu-latest
    steps: 
      - name: job2-step1
        run: |
          echo "this si sjob2 "
