name: My first workflow

on:
  push:

jobs:
  myjob1:
    runs-on: ubuntu-latest
    steps:
      - name: displaying a msg
        run: echo "this is my first workflow"
      - name: hello
        run: |
          echo "how r u ?"
          echo "hi i am fine"
    