name: Outputs Demo
on:
    workflow_dispatch: 


jobs:
    job1:
        runs-on: ubuntu-slim
        outputs:
          myname: "${{steps.josh.outputs.name}}"
          myjob: "${{steps.josh.outputs.job}}"

        steps:
            - name: my step1
              id: josh
              run: |
                echo "this is job1"
                echo "name=josh" >> "$GITHUB_OUTPUT "
                echo "job=josh" >> " $GITHUB_OUTPUT "
            
            - name: my step2
              run: |
                 echo "${{steps.josh.outputs.name}}"
                 echo "${{steps.josh.outputs.job}}"



    job2:
        runs-on: ubuntu-slim
        needs: job1
        steps:
            - name: my step2
              run: |
                echo "this is job2"
                echo "${{needs.job1.outputs.myname}}"
                echo "${{needs.job1.outputs.myjob}}"

                